# Generated by Django 4.2.17 on 2025-03-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challengeName", models.TextField()),
                ("challengeDifficulty", models.CharField(max_length=50)),
            ],
        ),
    ]
